"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:b1)\
$os\
$username\
$directory\
[](bg:b2 fg:b1)\
$git_branch\
$git_commit\
$git_status\
$git_state\
[](bg:b3 fg:b2)\
$aws\
[](bg:b4 fg:b3)\
$golang\
$java\
$kotlin\
$lua\
$nodejs\
$php\
$python\
$ruby\
$rust\
$scala\
$terraform\
[](fg:b4)\
$fill\
[](fg:b3)\
$status\
[](bg:b3 fg:b2)\
$cmd_duration\
[](bg:b2 fg:b1)\
$time\
[](fg:b1)\
\n$character\
"""

# right_format = """
# $cmd_duration
# """

palette = 'soheee'

[os]
style = "bg:b1 fg:f1"
disabled = false

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[directory]
style = "bg:b1 fg:f2"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = '   '
style = "bg:b2 fg:f2"
format = "[ $symbol$branch(:$remote_branch) ]($style)"

[git_commit]
style = "bg:b2 fg:f2"

[git_status]
style = "bg:b2 fg:f2"
format = '([\[$all_status$ahead_behind\] ]($style))'

[git_state]
style = "bg:b2 fg:f2"
format = '[\($state( $progress_current of $progress_total)\)]($style)'

[aws]
style = 'bg:b3 fg:f3'
symbol = "󰸏 "
format = '[ $symbol ($profile)]($style)'

[gcloud]
symbol = " "

[golang]
style = "bg:b4 fg:f4"
symbol = " "
format = "[ $symbol($version )]($style)"

[java]
style = "bg:b4 fg:f4"
symbol = " "
format = "[ $symbol($version )]($style)"

[kotlin]
style = "bg:b4 fg:f4"
symbol = " "
format = "[ $symbol($version )]($style)"

[lua]
style = "bg:b4 fg:f4"
symbol = " "
format = "[ $symbol($version )]($style)"

[nodejs]
style = "bg:b4 fg:f4"
symbol = " "
format = "[ $symbol($version )]($style)"

[php]
style = "bg:b4 fg:f4"
symbol = " "
format = "[ $symbol($version )]($style)"

[python]
style = "bg:b4 fg:f4"
symbol = " "
format = "[ $symbol($version )]($style)"

[ruby]
style = "bg:b4 fg:f4"
symbol = " "
format = "[ $symbol($version )]($style)"

[rust]
style = "bg:b4 fg:f4"
symbol = "󱘗 "
format = "[ $symbol($version )]($style)"

[scala]
style = "bg:b4 fg:f4"
symbol = " "
format = "[ $symbol($version )]($style)"

[terraform]
style = "bg:b4 fg:f4"
symbol = " "
format = "[ $symbol($version )]($style)"

[mise]
style = "bg:b4 fg:f4"
disabled = false

[fill]
symbol = '─'
style = 'b4'

[line_break]
disabled = false

[status]
style = "bg:b3"
format = '[ $symbol ]($style)'
symbol = '[✘](bg:b3 fg:red)'
success_symbol = '[✔](bg:b3 fg:green)'
not_executable_symbol = '[✘](bg:b3 fg:red)'
not_found_symbol = '[✘](bg:b3 fg:red)'
map_symbol = true
disabled = false

[cmd_duration]
min_time = 1
style = "bg:b2 fg:f2"
show_milliseconds = true
format = '[ 󰚭 $duration ]($style)'
disabled = false

[time]
time_format = "%T"
style = "bg:b1 fg:f1"
format = '[  $time ]($style)'
disabled = false

[character]
success_symbol = '[❯](green)'
error_symbol = '[❯](red)'
disabled = false

[palettes.soheee]
b1 = '235'
b2 = '238'
b3 = '241'
b4 = '244'
f1 = 'white'
f2 = 'white'
f3 = 'white'
f4 = 'white'
